FROM node:8.16.2-buster-slim

ENV SERVER_FOLDER /opt/app/
RUN mkdir -p $SERVER_FOLDER
WORKDIR $SERVER_FOLDER

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

ENV NODE_INSPECT_PORT=${NODE_INSPECT_PORT:-5858}
ENV NODE_SERVER_PORT=${NODE_SERVER_PORT:-8080}

COPY server/ $SERVER_FOLDER/server
COPY config/ $SERVER_FOLDER/config
COPY node_modules $SERVER_FOLDER/node_modules
COPY build $SERVER_FOLDER/build

EXPOSE $NODE_SERVER_PORT $NODE_INSPECT_PORT

ENTRYPOINT exec node --inspect=$NODE_INSPECT_PORT ./server/server.js
